# Generated by Django 3.0 on 2020-08-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.BigIntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
